name: Daily Stock Update

on:
  schedule:
    # 毎日日本時間の朝9時（世界標準時の0時）に実行
    - cron: '0 0 * * *'
  workflow_dispatch: # 手動でテスト実行するためのボタン

jobs:
  update_stock:
    runs-on: ubuntu-latest
    steps:
      - name: Call Update Stock URL
        run: |
          curl -X GET https://cat-food-jj1d.onrender.com/cron/update-stock
